name: Tests

on:
  pull_request:
    branches: [ master ]
    paths-ignore: [  ]

jobs:
  test:
    name: Running 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1

    - name: Install
      run: npm install

    - name: Test
      run: npm test:ci
